FROM nginx

COPY ./nginx-1.25.3/conf/nginx.conf /etc/nginx/conf/nginx.conf
COPY ./nginx-1.25.3/html/index_phone.html /etc/nginx/html/index_phone.html
COPY ./nginx-1.25.3/html/default_image.jpg /etc/nginx/html/default_image.jpg
